---
 - hosts: 127.0.0.1
   connection: local
   tasks:
     - name: creating inventory
       lineinfile:
         path: /home/ubuntu/python/inventory
         line: "{{item.line}}"
         state: present
         create: yes
       with_items: 
         - {line: '[tomcat:vars]'}
         - {line: 'ansible_user=ec2-user'}
         - {line: 'ansible_private_key_file=/home/ubuntu/python/a.pem'}
         - {line: '[tomcat]'}
